### ISSUE TITLE
If 2 players pours beer at the same time it goes twice as fast.

### ISSUE THREAD

**Issue by DreamingJohnny** [smeas/Beer-and-Plunder#136]
**Describe the bug**
Atm two players can cooperate to tap up a beer twice as fast from the BeerTap. This shouldn't really be possible,

**Expected behavior**
My suggestion is that a BeerTap shouldn't be usable when in use by an other player.

**Additional context**
Please check back with me (Johan) if you solve this, since I will need to implement a similar solution with the Barrel Refill station.

**Comment by MrJackey** [comment]
Fixed in #142
